2019-02-19 18:26:17,498 - default - ERROR - Exception occurred
Traceback (most recent call last):
  File "Trading/Dataset/Dataset.py", line 629, in computeFeatures
    while idx_from < len(self.df.index):
AttributeError: 'NoneType' object has no attribute 'index'
2019-02-19 18:26:39,406 - default - ERROR - Exception occurred
Traceback (most recent call last):
  File "Trading/Dataset/Dataset.py", line 629, in computeFeatures
    while idx_from < len(self.df.index):
AttributeError: 'NoneType' object has no attribute 'index'
