2019-02-27 16:33:25,053 - default - ERROR - Exception occurred
Traceback (most recent call last):
  File "Trading/Dataset/Dataset.py", line 636, in computeFeatures
    while idx_from < len(self.df.index):
AttributeError: 'NoneType' object has no attribute 'index'
2019-02-27 16:33:25,057 - default - ERROR - Exception occurred
Traceback (most recent call last):
  File "Trading/Dataset/Dataset.py", line 636, in computeFeatures
    while idx_from < len(self.df.index):
AttributeError: 'NoneType' object has no attribute 'index'
2019-02-27 16:33:25,059 - default - ERROR - Exception occurred
Traceback (most recent call last):
  File "Trading/Dataset/Dataset.py", line 636, in computeFeatures
    while idx_from < len(self.df.index):
AttributeError: 'NoneType' object has no attribute 'index'
2019-02-27 16:33:25,177 - default - ERROR - Exception occurred
Traceback (most recent call last):
  File "Trading/Dataset/Dataset.py", line 636, in computeFeatures
    while idx_from < len(self.df.index):
AttributeError: 'NoneType' object has no attribute 'index'
