2019-03-05 18:05:20,041 - default - ERROR - Exception occurred
Traceback (most recent call last):
  File "Trading/Dataset/Dataset.py", line 640, in computeFeatures
    while idx_from < len(self.df.index):
AttributeError: 'NoneType' object has no attribute 'index'
2019-03-05 18:05:20,043 - default - ERROR - Exception occurred
Traceback (most recent call last):
  File "Trading/Dataset/Dataset.py", line 640, in computeFeatures
    while idx_from < len(self.df.index):
AttributeError: 'NoneType' object has no attribute 'index'
2019-03-05 18:35:14,806 - default - ERROR - Exception occurred
Traceback (most recent call last):
  File "Trading/Dataset/Dataset.py", line 640, in computeFeatures
    while idx_from < len(self.df.index):
AttributeError: 'NoneType' object has no attribute 'index'
2019-03-05 18:35:14,851 - default - ERROR - Exception occurred
Traceback (most recent call last):
  File "Trading/Dataset/Dataset.py", line 640, in computeFeatures
    while idx_from < len(self.df.index):
AttributeError: 'NoneType' object has no attribute 'index'
2019-03-05 18:35:24,609 - default - ERROR - Exception occurred
Traceback (most recent call last):
  File "Trading/Dataset/Dataset.py", line 640, in computeFeatures
    while idx_from < len(self.df.index):
AttributeError: 'NoneType' object has no attribute 'index'
2019-03-05 18:35:24,614 - default - ERROR - Exception occurred
Traceback (most recent call last):
  File "Trading/Dataset/Dataset.py", line 640, in computeFeatures
    while idx_from < len(self.df.index):
AttributeError: 'NoneType' object has no attribute 'index'
