2018-12-23 00:44:45,088 - default - ERROR - Exception occurred
Traceback (most recent call last):
  File "Trading/Dataset/Dataset.py", line 626, in computeFeatures
    while idx_from < len(self.df.index):
AttributeError: 'NoneType' object has no attribute 'index'
